Web/Models/ErrorViewModel.cs
namespace Web.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

Web/Areas/Admin/Controllers/CategoryController.cs
using Domain.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Services;

namespace Web.Areas.Admin.Controllers;
[Area("admin")]
[Authorize]
public class CategoryController : Controller
{
    private readonly CategoryServices _services;

    public CategoryController(CategoryServices services)
    {
        _services = services;
    }
    
    [HttpGet]
    public async Task<IActionResult> Index()
    {
        var list = await _services.GetCategories();
        return View(list);
    }
    
    [HttpGet]
    public IActionResult Create()
    {
        return View(new CategoryDto());
    }
    
    [HttpPost]
    public async Task<IActionResult> Create(CategoryDto categoryDto)
    {
        if (ModelState.IsValid)
        {
            await _services.InsertCategory(categoryDto);
            return RedirectToAction("Index");
        }

        return View(categoryDto);
    }
    
    [HttpGet]
    public async Task<IActionResult> Edit(int id)
    {
        var find = await _services.GetCategoryById(id);
        return View(find);
    }
    
    [HttpPost]
    public async Task<IActionResult> Edit(CategoryDto categoryDto)
    {
        if (ModelState.IsValid)
        {
            await _services.UpdateCategory(categoryDto);
            return RedirectToAction("Index");
        }

        return View(categoryDto);
    }

    [HttpGet]
    public async Task<IActionResult> Delete(int id)
    {
        await _services.DeleteCategory(id);
        return RedirectToAction("Index");
    }
}

Web/Areas/Admin/Controllers/CustomerController.cs
using Domain.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Services;

namespace Web.Areas.Admin.Controllers;
[Area("admin")]
[Authorize]

public class CustomerController : Controller
{
    private readonly CustomerServices _services;

    public CustomerController(CustomerServices services)
    {
        _services = services;
    }
    
    [HttpGet]
    public async Task<IActionResult> Index()
    {
        var list = await _services.GetCustomers();
        return View(list);
    }
    
    [HttpGet]
    public IActionResult Create()
    {
        return View(new CustomerDto());
    }
    
    [HttpPost]
    public async Task<IActionResult> Create(CustomerDto customerDto)
    {
        if (ModelState.IsValid)
        {
            await _services.InsertCustomer(customerDto);
            return RedirectToAction("Index");
        }

        return View(customerDto);
    }
    
    [HttpGet]
    public async Task<IActionResult> Edit(int id)
    {
        var find = await _services.GetCustomerById(id);
        return View(find);
    }
    
    [HttpPost]
    public async Task<IActionResult> Edit(CustomerDto customerDto)
    {
        if (ModelState.IsValid)
        {
            await _services.UpdateCustomer(customerDto);
            return RedirectToAction("Index");
        }

        return View(customerDto);
    }

    [HttpGet]
    public async Task<IActionResult> Delete(int id)
    {
        await _services.DeleteCustomer(id);
        return RedirectToAction("Index");
    }
}

Web/Areas/Admin/Controllers/ProductController.cs
using Domain.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Services;

namespace Web.Areas.Admin.Controllers;
[Area("admin")]
[Authorize]
public class ProductController : Controller
{
    private readonly ProductServices _services;
    private readonly CategoryServices _categoryServices;

    public ProductController(ProductServices services, CategoryServices categoryServices)
    {
        _services = services;
        _categoryServices = categoryServices;
    }
    
    [HttpGet]
    public async Task<IActionResult> Index()
    {
        var list = await _services.GetProducts();
        return View(list);
    }

    [HttpGet]
    public async Task<IActionResult> Create()
    {
        ViewBag.Categories = await _categoryServices.GetCategories();
        return View(new ProductDto());
    }
    
    [HttpPost]
    public async Task<IActionResult> Create(ProductDto productDto)
    {
        ViewBag.Categories = await _categoryServices.GetCategories();
        if (ModelState.IsValid)
        {
            await _services.InsertProduct(productDto);
            return RedirectToAction("Index");
        }

        return View(productDto);
    }
    
    [HttpGet]
    public async Task<IActionResult> Edit(int id)
    {
        ViewBag.Categories = await _categoryServices.GetCategories();
        var find = await _services.GetProductById(id);
        return View(find);
    }
    
    [HttpPost]
    public async Task<IActionResult> Edit(ProductDto productDto)
    {
        ViewBag.Categories = await _categoryServices.GetCategories();
        if (ModelState.IsValid)
        {
            await _services.UpdateProduct(productDto);
            return RedirectToAction("Index");
        }

        return View(productDto);
    }

    [HttpGet]
    public async Task<IActionResult> Delete(int id)
    {
        await _services.DeleteProduct(id);
        return RedirectToAction("Index");
    }
}

Web/Controllers/AccountController.cs
using System.Security.Claims;
using Domain;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Services.Account;


public class AccountController:Controller   
{
    private readonly SignInManager<IdentityUser> _signInManager;
    private readonly AccountService _accountService;

    public AccountController(SignInManager<IdentityUser> signInManager, AccountService accountService)
    {
        _signInManager = signInManager;
        _accountService = accountService;
    }
    
    [HttpGet]
    public IActionResult Login(string returnUrl)
    {
        return View(new Login() { ReturnUrl = returnUrl });
    }
   
    
    [HttpPost]
    public async Task<IActionResult> Login(Login model)
    {
        if (ModelState.IsValid)
        {
            var user = await _accountService.Login(model);
            if (user == null) return View(model);
            await _signInManager.SignInAsync(user, false, null);
            
            if(!string.IsNullOrEmpty(model.ReturnUrl))
            { 
                return Redirect(model.ReturnUrl); 
            }
        }

        return RedirectToAction("Index", "Home");
    }
    
    [HttpGet]
    public IActionResult Register()
    {
        return View(new Register());
    }

    [HttpPost]
    public async Task<IActionResult> Register(Register model)
    {
        if (!ModelState.IsValid) return View(model);
        await _accountService.Register(model);
        return RedirectToAction("Index", "Home");
    }

    public async Task<IActionResult> Logout()
    {
        await _signInManager.SignOutAsync();
        return RedirectToAction("Index","Home");
    }
    
}

Web/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Web.Models;

namespace Web.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }
    
    [Authorize]
    public IActionResult _Layout()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

Web/Areas/Admin/Views/Category/Create.cshtml
@model Domain.Models.CategoryDto



<form asp-action="Create"  method="post">
    <div class="row">
        <div class="col-lg-12">
            <div class="form-group">
                 <label>Category Name</label>
                <input asp-for="CategoryName" type="text" class="form-control " placeholder="" tabindex="1">
            </div>

            
            <div class="form-group">
                <div asp-validation-summary="All" class="text-danger"></div>
            </div>
            <div class="card-footer">
                <center>
                    <button type="submit" class="btn btn-success">Submit</button>
                    <a asp-action="Index" asp-controller="Category" class="btn btn-secondary">Cancle</a>
                </center>
            </div>
        </div>
    </div>
</form>

Web/Areas/Admin/Views/Category/Edit.cshtml
@model Domain.Models.CategoryDto



<form asp-action="Edit" method="post">
    <input asp-for="CategoryId" type="hidden"/>
    <div class="row">
        <div class="col-lg-12">
            <div class="form-group">
                <label>Category Name</label>
                <input asp-for="CategoryName" type="text" class="form-control " placeholder="" tabindex="1">
            </div>


            <div class="form-group">
                <div asp-validation-summary="All" class="text-danger"></div>
            </div>
            <div class="card-footer">
                <center>
                    <button type="submit" class="btn btn-warning">Submit</button>
                    <a asp-action="Index" asp-controller="Category" class="btn btn-secondary">Cancle</a>
                </center>
            </div>
        </div>
    </div>
</form>

Web/Areas/Admin/Views/Category/Index.cshtml
@model List<Domain.Models.CategoryDto>


<div class="row">
    <div class="col-md-12">
        <a asp-action="Create" asp-controller="Customer" class="btn btn-success">Create</a>
    </div>
</div>

<div class="col-lg-12 grid-margin stretch-card">
    <div class="card">
        <div class="card-body">
            <h4 class="card-title">Products Table</h4>
            <p class="card-description">
                Add class <code>.table-hover</code>
            </p>
            <div class="table-responsive">
                <table class="table table-hover">
                    <thead>
                    <tr>
                        <th>Category Name</th>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>

                            <td>@item.CategoryName</td>

                            <td>
                                <a class="nav-link text-dark" asp-action="Edit" asp-controller="Customer" asp-route-id="@item.CategoryId">
                                    Edit
                                </a>
                                <a class="nav-link text-dark" asp-action="Delete" asp-controller="Customer" asp-route-id="@item.CategoryId">
                                    Delete
                                </a>
                            </td>
                        </tr>
                    }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

Web/Areas/Admin/Views/Customer/Create.cshtml
@model Domain.Models.CustomerDto



<form asp-action="Create"  method="post">
    <div class="row">
        <div class="col-lg-12">
            <div class="form-group">
                 <label>Customer Name</label>
                <input asp-for="CustomerName" type="text" class="form-control " placeholder="" tabindex="1">
            </div>
            <div class="form-group">
                <label>Customer Address</label>
                <input asp-for="CustomerAddress" type="text" class="form-control" placeholder="" tabindex="2">
            </div>
            @*<div class="form-group">
                <label>Курс ID:</label>
                <input asp-for="CourseId" type="number" class="form-control" placeholder="Введите курс Id" tabindex="2">
            </div>*@
            

             @* <div class="form-group"> *@
             @*     $1$          <label>Названия курса:</label> #1# *@
             @*     $1$ <select class="form-select" asp-for="CourseId" asp-items="@(new SelectList(ViewBag.Courses,"Id","Name"))" > #1# *@
             @*     $1$      <option value="0" selected>Open this select menu</option> #1# *@
             @*     $1$ </select> #1# *@
             @* *@
             @*  </div> *@
            
           
            <div class="form-group">
                <div asp-validation-summary="All" class="text-danger"></div>
            </div>
            <div class="card-footer">
                <center>
                    <button type="submit" class="btn btn-success">Submit</button>
                    <a asp-action="Index" asp-controller="Customer" class="btn btn-secondary">Cancle</a>
                </center>
            </div>
        </div>
    </div>
</form>

Web/Areas/Admin/Views/Customer/Edit.cshtml
@model Domain.Models.CustomerDto



<form asp-action="Edit" method="post">
    <input asp-for="CustomerId" type="hidden"/>
    <div class="row">
        <div class="col-lg-12">
            <div class="form-group">
                <label>Customer Name</label>
                <input asp-for="CustomerName" type="text" class="form-control " placeholder="" tabindex="1">
            </div>
            <div class="form-group">
                <label>Customer Address</label>
                <input asp-for="CustomerAddress" type="text" class="form-control" placeholder="" tabindex="2">
            </div>
            @*<div class="form-group">
                <label>Курс ID:</label>
                <input asp-for="CourseId" type="number" class="form-control" placeholder="Введите курс Id" tabindex="2">
            </div>*@


            @* <div class="form-group"> *@
            @*     $1$          <label>Названия курса:</label> #1# *@
            @*     $1$ <select class="form-select" asp-for="CourseId" asp-items="@(new SelectList(ViewBag.Courses,"Id","Name"))" > #1# *@
            @*     $1$      <option value="0" selected>Open this select menu</option> #1# *@
            @*     $1$ </select> #1# *@
            @* *@
            @*  </div> *@


            <div class="form-group">
                <div asp-validation-summary="All" class="text-danger"></div>
            </div>
            <div class="card-footer">
                <center>
                    <button type="submit" class="btn btn-warning">Submit</button>
                    <a asp-action="Index" asp-controller="Customer" class="btn btn-secondary">Cancle</a>
                </center>
            </div>
        </div>
    </div>
</form>

Web/Areas/Admin/Views/Customer/Index.cshtml
@model List<Domain.Models.CustomerDto>


<div class="row">
    <div class="col-md-12">
        <a asp-action="Create" asp-controller="Customer" class="btn btn-success">Create</a>
    </div>
</div>

<div class="col-lg-12 grid-margin stretch-card">
    <div class="card">
        <div class="card-body">
            <h4 class="card-title">Products Table</h4>
            <p class="card-description">
                Add class <code>.table-hover</code>
            </p>
            <div class="table-responsive">
                <table class="table table-hover">
                    <thead>
                    <tr>
                        <th>Customer Name</th>
                        <th>Customer Address</th>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>

                            <td>@item.CustomerName</td>
                            <td>@item.CustomerAddress</td>

                            <td>
                                <a class="nav-link text-dark" asp-action="Edit" asp-controller="Customer" asp-route-id="@item.CustomerId">
                                    Edit
                                </a>
                                <a class="nav-link text-dark" asp-action="Delete" asp-controller="Customer" asp-route-id="@item.CustomerId">
                                    Delete
                                </a>
                            </td>
                        </tr>
                    }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

Web/Areas/Admin/Views/Product/Create.cshtml
@model Domain.Models.ProductDto


<form enctype="multipart/form-data" asp-action="Create" method="post" >
    <div class="row">
        <div class="col-lg-12">
            <div class="form-group">
                <label>Product Name</label>
                <input asp-for="ProductName" type="text" class="form-control " placeholder="" tabindex="1">
            </div>
            <div class="form-group">
                <label>Product Quantity</label>
                <input asp-for="ProductQuantity" type="text" class="form-control" placeholder="" tabindex="2">
            </div>
            <div class="form-group">
                <label>Product Price</label>
                <input asp-for="ProductPrice" type="text" class="form-control" placeholder="" tabindex="2">
            </div>
            <div class="form-group">
                <label>Product Image</label>
                <input asp-for="ProductImage" type="file" class="form-control" placeholder="" tabindex="2">
            </div>
            <div class="form-group">
                <div asp-validation-summary="All" class="text-danger"></div>
            </div>
            <div class="form-group">
                <label>Category Name</label>
                <select class="form-control" asp-for="CategoryId">
                    @foreach (var item in ViewBag.Categories)
                    {
                        <option value="@item.CategoryId">
                            @item.CategoryName
                        </option>
                    }

                </select>
                <span asp-validation-for="CategoryId"></span>
            </div>
            <div class="card-footer">
                <center>
                    <button type="submit" class="btn btn-primary">Submit</button>
                    <a asp-action="Index" asp-controller="Product" class="btn btn-secondary">Cancle</a>
                </center>
            </div>
        </div>
    </div>
</form>

Web/Areas/Admin/Views/Product/Edit.cshtml
@model Domain.Models.ProductDto


<form enctype="multipart/form-data" asp-action="Edit" method="post">
    <input asp-for="ProductId" type="hidden"/>
    <div class="row">
        <div class="col-lg-12">
            <div class="form-group">
                <label>Product Name</label>
                <input asp-for="ProductName" type="text" class="form-control " placeholder="" tabindex="1">
            </div>
            <div class="form-group">
                <label>Product Quantity</label>
                <input asp-for="ProductQuantity" type="text" class="form-control" placeholder="" tabindex="2">
            </div>
            <div class="form-group">
                <label>Product Price</label>
                <input asp-for="ProductPrice" type="text" class="form-control" placeholder="" tabindex="2">
            </div>
            <div class="form-group">
                <label>Product Image</label>
                <input asp-for="ProductImage" type="file" class="form-control" placeholder="" tabindex="2">
            </div>

            <div class="form-group">
                <div asp-validation-summary="All" class="text-danger"></div>
            </div>
            <div class="form-group">
                <label>Category Name</label>
                <select class="form-control" asp-for="CategoryId">
                    @foreach (var item in ViewBag.Categories)
                    {
                        <option value="@item.CategoryId">
                            @item.CategoryName
                        </option>
                    }

                </select>
                <span asp-validation-for="CategoryId"></span>
            </div>
            <div class="card-footer">
                <center>
                    <button type="submit" class="btn btn-warning">Submit</button>
                    <a asp-action="Index" asp-controller="Product" class="btn btn-secondary">Cancle</a>
                </center>
            </div>
        </div>
    </div>
</form>

Web/Areas/Admin/Views/Product/Index.cshtml
@model List<Domain.Models.ProductCategoriesDto>


<div class="row">
    <div class="col-md-12">
        <a asp-action="Create" asp-controller="Product" class="btn btn-success">Create</a>
    </div>
</div>

<div class="col-lg-12 grid-margin stretch-card">
    <div class="card">
        <div class="card-body">
            <h4 class="card-title">Products Table</h4>
            <p class="card-description">
                Add class <code>.table-hover</code>
            </p>
            <div class="table-responsive">
                <table class="table table-hover">
                    <thead>
                    <tr>
                        <td>Product Name</td>
                        <td>Product Quantity</td>
                        <td>Product Price</td>
                        <td>Category Name</td>
                        <td>Product Image</td>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>

                            <td>@item.ProductName</td>
                            <td>@item.ProductQuantity</td>
                            <td>@item.ProductPrice</td>
                            <td>@item.CategoryName</td>
                            <td><img src="~/Images/@item.ProductImage"/></td>

                            <td>
                                <a class="nav-link text-dark" asp-action="Edit" asp-controller="Product" asp-route-id="@item.ProductId">
                                    Edit 
                                </a>
                                <a class="nav-link text-dark"  asp-action="Delete" asp-controller="Product" asp-route-id="@item.ProductId">
                                    Delete 
                                </a>
                            </td>
                        </tr>
                    }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/Identity.styles.css" asp-append-version="true"/>
</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container-fluid">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Identity</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="Admin" asp-controller="Product" asp-action="Index">Admin</a>
                    </li>
                </ul>
                @if (User.Identity.IsAuthenticated)
                {
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a class="nav-link text-dark">@User.Identity.Name</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Account" asp-action="Logout">Logout</a>
                        </li>
                    </ul>
                }
                else
                {
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Account" asp-action="Login">Login</a>
                        </li>
                    </ul>
                }

            </div>
        </div>
    </nav>
</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>


<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>